### ISSUE TITLE
v1.6.0 server crash on startup

### ISSUE THREAD

**Issue by awdwyn** [Devoev/vanilla-cubed#8]
Many many mods installed so this could very well be a conflict, but I get a crash on startup with the following message in my server log:

`[10:38:32] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'vanilla_cubed'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.22.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.22-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.ExceptionInInitializerError
        at net.devoev.vanilla_cubed.VanillaCubed.onInitialize(VanillaCubed.kt:36) ~[vanilla-cubed-1.20.1-1.6.0.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
        ... 8 more
Caused by: java.lang.RuntimeException: Cannot load class net.devoev.vanilla_cubed.screen.ModScreenHandlerTypes in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.devoev.vanilla_cubed.client.gui.screen.ingame.ModScreens.<clinit>(ModScreens.kt:18) ~[vanilla-cubed-1.20.1-1.6.0.jar:?]
        at net.devoev.vanilla_cubed.VanillaCubed.onInitialize(VanillaCubed.kt:36) ~[vanilla-cubed-1.20.1-1.6.0.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
        ... 8 more`

Full log file is attached.
[latest.log](https://github.com/Devoev/vanilla-cubed/files/12569179/latest.log)

**Comment by Devoev** [comment]
Thanks for the info, that's a bug in the mod; should be fixed now. I will release the fix in the next update

**Comment by Devoev** [comment]
Should be fixed in 1.6.1. Can you confirm if it works now?

**Comment by awdwyn** [comment]
Confirming that it does indeed load on the server and client, and all recipes (as far as I can tell) are visible in REI. No test done beyond that. The only mentions of this mod in the server log are the initial fabric load and then a few more as follows:

`	- vanilla_cubed 1.20.1-1.6.1

[16:44:41] [main/WARN]: Adding vanilla_cubed:magnetic to saved/remote registry.

[16:44:41] [main/WARN]: Adding vanilla_cubed:nourishment to saved/remote registry.

[16:44:41] [main/WARN]: Adding vanilla_cubed:reach to saved/remote registry.
`

**Comment by Devoev** [comment]
thats great. If you encounter any other problem let me know

**Comment by awdwyn** [comment]
Ok I got one for you :D Crashed while 3 of us were on my server, and I was fighting Pillagers.

`[10:33:01] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method net.devoev.vanilla_cubed.block.entity.beacon.upgrades.DisableGearDamageUpgrade.preventItemDamage, parameter player
	at net.devoev.vanilla_cubed.block.entity.beacon.upgrades.DisableGearDamageUpgrade.preventItemDamage(DisableGearDamageUpgrade.kt) ~[vanilla-cubed-1.20.1-1.6.1.jar:?]
	at net.minecraft.class_1799.handler$dnf000$vanilla_cubed$preventItemDamage(class_1799.java:6594) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.method_7970(class_1799.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.method_7956(class_1799.java:375) ~[server-intermediary.jar:?]
	at net.minecraft.class_1764.method_7763(class_1764.java:242) ~[server-intermediary.jar:?]
	at net.minecraft.class_1764.method_7777(class_1764.java:277) ~[server-intermediary.jar:?]
	at net.minecraft.class_3745.method_24654(class_3745.java:31) ~[server-intermediary.jar:?]
	at net.minecraft.class_1604.method_7105(class_1604.java:220) ~[server-intermediary.jar:?]
	at net.minecraft.class_1383.method_6268(class_1383.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_4135.method_6268(class_4135.java:65) ~[server-intermediary.jar:?]
	at net.minecraft.class_1355.method_38849(class_1355.java:120) ~[server-intermediary.jar:?]
	at net.minecraft.class_1355.method_6275(class_1355.java:111) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.method_6023(class_1308.java:771) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2673) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.method_6007(class_1308.java:550) ~[server-intermediary.jar:?]
	at net.minecraft.class_1588.method_6007(class_1588.java:44) ~[server-intermediary.jar:?]
	at net.minecraft.class_3763.method_6007(class_3763.java:114) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:351) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	... 5 more
[10:33:01] [Server thread/ERROR]: This crash report has been saved to: C:\Servers\Minecraft Java 2\.\crash-reports\crash-2023-09-13_10.33.01-server.txt
`
[crash-2023-09-13_10.34.02-server.txt](https://github.com/Devoev/vanilla-cubed/files/12599945/crash-2023-09-13_10.34.02-server.txt)

[latest.log](https://github.com/Devoev/vanilla-cubed/files/12599944/latest.log)

**Comment by Devoev** [comment]
that bug should already be fixed in 1.6.2 ;)

**Comment by awdwyn** [comment]
Beautiful thank you, I'll install that when I have the opportunity :)

**Comment by Devoev** [comment]
your welcome, have fun!
