### ISSUE TITLE
Some Gear/Item Damage related server crashes

### ISSUE THREAD

**Issue by DaytonaBlep** [Devoev/vanilla-cubed#9]
I'm not sure exactly what the problem is, I have a lot of mods installed, but my server is crashing and the last thing I hear is a shot of pillager's crossbow. I also saw references to Vanilla Cubed and decided that you can help me.

```
Description: Ticking entity

java.lang.NullPointerException: Parameter specified as non-null is null: method net.devoev.vanilla_cubed.block.entity.beacon.upgrades.DisableGearDamageUpgrade.preventItemDamage, parameter player
	at net.devoev.vanilla_cubed.block.entity.beacon.upgrades.DisableGearDamageUpgrade.preventItemDamage(DisableGearDamageUpgrade.kt)
	at net.minecraft.class_1799.handler$ilp000$vanilla_cubed$preventItemDamage(class_1799.java:12594)
	at net.minecraft.class_1799.method_7970(class_1799.java)
	at net.minecraft.class_1799.method_7956(class_1799.java:375)
	at net.minecraft.class_1764.method_7763(class_1764.java:242)
	at net.minecraft.class_1764.method_7777(class_1764.java:277)
	at net.minecraft.class_3745.method_24654(class_3745.java:31)
	at net.minecraft.class_1604.method_7105(class_1604.java:220)
	at net.minecraft.class_1383.method_6268(class_1383.java:143)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1308.method_6023(class_1308.java:779)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_3763.method_6007(class_3763.java:114)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

This is repeated over and over again if I try to log in to the game.
Also full crash report file is attached: [crash-2023-09-12_14.28.46-server.txt](https://github.com/Devoev/vanilla-cubed/files/12586011/crash-2023-09-12_14.28.46-server.txt)

**Comment by Devoev** [comment]
Seems like a bug on my side. Will try to fix it in the next release

**Comment by Devoev** [comment]
version 1.6.2 should fix the bug, can you confirm whether it works now?

**Comment by DaytonaBlep** [comment]
I haven't been able to reproduce this bug for a long time, yes, I think it's fixed

**Comment by Devoev** [comment]
perfect, thanks for letting me know!
